### ISSUE TITLE
Update testing driver script so it can be run from Windows too

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKPerformanceBenchmarking#43]
[testing driver](https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/blob/master/ITK_PerformanceTestingDriver.sh) bash script

**Comment by blowekamp** [comment]
I always is stall git with git bash on my build systems. I don’t always install python.

**Comment by blowekamp** [comment]
I would expect that to be easier than rewriting it in python.
