### ISSUE TITLE
Increase benchmarking automation in Windows

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKPerformanceBenchmarking#53]
As noted in PR #44, every time a Windows user wants to run the benchmarks, and if they use MSVC as the build tool, they need to be careful with the contents of the path contained in [RunWithVisualStudio.cmd](https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/blob/master/RunWithVisualStudio.cmd), since the first line points to the path of the `vcvars*.bat` command file, which may vary across Windows and MSVC versions and the chosen installation directory.

It may be worthwhile investigating how this step can be automated or avoided.

**Comment by thewtex** [comment]
We now have the `evaluate-itk-performance.py` cross-platform script.

**Comment by jhlegarreta** [comment]
:1st_place_medal: Thanks Matt ! I hope to be able to test the script at some point !
